# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('categories', models.CharField(choices=[('clothes', 'Clothes'), ('appliances', 'Appliances'), ('furniture', 'Furniture')], max_length=10)),
            ],
        ),
    ]
