# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=256),
        ),
    ]
